spring:
  profiles: 
    active:
    - dev
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
      
//  datasource:
//    type: com.zaxxer.hikari.HikariDataSource
//    driver-class-name: com.mysql.jdbc.Driver
//    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf8
//    username: root
//    password: 1234
//    hikari:
//      maximum-pool-size: 10
//      max-lifetime: 30      


security:
  basic:
    enabled: false  
    
    
server:
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    uri-encoding: UTF-8
    