spring:
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  messages:
    encoding: UTF-8
    always-use-message-format: false
    cache-seconds: -1
    basename: messages/message-framework, messages/validation 

security:
  basic:
    enabled: false  

# EMBEDDED SERVER CONFIGURATION (ServerProperties) ================    
server:
  port: 8282
  context-path: /kai-server
  jsp-servlet:
    init-parameters:
      development: true
  tomcat:
    uri-encoding: UTF-8

## LOGGING ========================================================
logging:
  config: classpath:logback-spring.xml