# ===================================================================
# COMMON SPRING BOOT PROPERTIES
#
# This sample file is provided as a guideline. Do NOT copy it in its
# entirety to your own application.               ^^^
# 
# Reference Site : http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#
# ===================================================================

# EMBEDDED SERVER CONFIGURATION (ServerProperties)  ==========================
server:
  port: 4242
  context-path: /kai-server

## LOGGING ========================================================
logging:
  config: classpath:logback-spring.xml